import { CSSProperties } from "react";

export const GAMEPAD_TESTER_STYLES: { [key: string]: CSSProperties } = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "#1a1a1a",
    color: "#e0e0e0",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
  },
  header: {
    background: "#2a2a2a",
    padding: "20px 40px",
    borderBottom: "1px solid #3a3a3a",
  },
  h1: {
    fontSize: "24px",
    fontWeight: 600,
    color: "#ffffff",
    margin: 0,
  },
  gamepadId: {
    fontSize: "18px",
    color: "#b0b0b0",
    marginTop: "8px",
    fontWeight: 400,
  },
  infoGrid: {
    display: "flex",
    gap: 0,
    padding: 0,
    background: "#222",
    flexWrap: "wrap",
  },
  infoItem: {
    flex: "1 1 20%",
    display: "flex",
    flexDirection: "column",
    padding: "16px 20px",
    borderRight: "1px solid #3a3a3a",
    borderBottom: "1px solid #3a3a3a",
    minWidth: 0,
  },
  infoItemLast: {
    borderRight: "none",
  },
  infoLabel: {
    fontSize: "11px",
    color: "#888",
    textTransform: "uppercase",
    fontWeight: 600,
    letterSpacing: "0.8px",
    marginBottom: "8px",
  },
  infoValue: {
    fontSize: "15px",
    fontWeight: 500,
    color: "#e0e0e0",
  },
  infoValueConnected: {
    color: "#4ade80",
  },
  infoValueDisconnected: {
    color: "#f87171",
  },
  mainContent: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 0,
    flex: 1,
    minHeight: 0,
  },
  leftPanel: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    padding: "40px",
    background: "#1a1a1a",
    borderRight: "1px solid #3a3a3a",
    overflowY: "auto",
  },
  buttonsSection: {
    marginBottom: "40px",
  },
  sectionTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    marginBottom: "20px",
  },
  buttonsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(8, 1fr)",
    gap: "8px",
  },
  buttonCell: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px 8px",
    background: "#252525",
    borderRadius: "8px",
    textAlign: "center",
    minHeight: "80px",
    transition: "all 0.1s ease",
  },
  buttonCellPressed: {
    background: "#3a3a3a",
  },
  buttonLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: "#666",
    marginBottom: "8px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  buttonValue: {
    fontSize: "20px",
    fontWeight: 700,
    color: "#e0e0e0",
    fontFamily: "'SF Mono', 'Monaco', 'Courier New', monospace",
  },
  buttonValuePressed: {
    color: "#4ade80",
  },
  axesSection: {
    marginBottom: "40px",
  },
  sticksSection: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    alignItems: "start",
  },
  stickContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
  },
  stickLabel: {
    fontSize: "12px",
    fontWeight: 600,
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: "0.8px",
  },
  stickVisualization: {
    position: "relative",
    width: "180px",
    height: "180px",
    background: "#252525",
    border: "2px solid #3a3a3a",
    borderRadius: "50%",
    boxShadow: "inset 0 2px 8px rgba(0, 0, 0, 0.3)",
  },
  stickDot: {
    position: "absolute",
    width: "16px",
    height: "16px",
    background: "#e0e0e0",
    border: "3px solid #4ade80",
    borderRadius: "50%",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    transition: "all 0.05s ease-out",
    boxShadow: "0 2px 8px rgba(74, 222, 128, 0.5)",
  },
  stickValues: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
    width: "100%",
  },
  valueItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "12px",
    background: "#252525",
    borderRadius: "6px",
  },
  valueLabel: {
    fontSize: "10px",
    fontWeight: 600,
    color: "#666",
    marginBottom: "6px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  valueNumber: {
    fontSize: "16px",
    fontWeight: 600,
    color: "#e0e0e0",
    fontFamily: "'SF Mono', 'Monaco', 'Courier New', monospace",
  },
  controlsSection: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
    marginTop: "24px",
  },
  controlButton: {
    flex: 1,
    minWidth: "140px",
    padding: "14px 20px",
    background: "#252525",
    border: "2px solid #3a3a3a",
    borderRadius: "8px",
    fontSize: "13px",
    fontWeight: 600,
    color: "#e0e0e0",
    cursor: "pointer",
    transition: "all 0.2s ease",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  controlButtonHover: {
    background: "#2a2a2a",
    borderColor: "#4a4a4a",
  },
  controlButtonActive: {
    background: "#4ade80",
    color: "#1a1a1a",
    borderColor: "#4ade80",
  },
  vibrationStatus: {
    fontSize: "12px",
    color: "#888",
    marginTop: "12px",
    textAlign: "center",
  },
  gamepadVisual: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#1a1a1a",
    padding: "40px",
    overflow: "auto",
  },
  gamepadSvgContainer: {
    width: "100%",
    maxWidth: "500px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  gamepadSvg: {
    width: "100%",
    height: "auto",
  },
};
